##
## docker-compose.yml edited by k-san based on official docker-compose.yml of FredBoat.
##

version: '3'
services:

  ################################################################################
  ##                               Database
  ################################################################################
  db:
    build: ./docker/db/
    restart: always

  ################################################################################
  ##                               FredBoat
  ################################################################################
  bot:
    build: ./docker/bot/
    restart: on-failure:3
    depends_on:
      - db
    #ports:
    #  - 1356:1356
    volumes:
      - ./logs:/opt/FredBoat/logs
      - ./music_persistence:/opt/FredBoat/music_persistence
